image:
  file: .gitpod/Dockerfile
tasks:
  - name: golang live
    init: |
      go install gotest.tools/gotestsum@latest
      go get && go build ./...

    command: |
      cp .env-sample .env
      air
    
vscode:
  extensions:
    - golang.go